### PR TITLE
增加記憶多組帳號功能

### PR DESCRIPTION
**Pull request by xnum**
只有source code
麻煩您再編譯與更新說明文件
thanks

### CODE REVIEW

**Comment by kevin940726** [comment]
Nice work! 
I rarely work on my windows lately :p. Give me some time to re-setup the environment and ~~learn how to code in C#~~ (Seriously, I bet you already knew it). I will let you know ASAP. Thanks.

**Comment by xnum** [comment]
Hi kevin,
If you are busy, I am pleased to help you release new version on github,
or just add me to the collaborators :p

**Comment by kevin940726** [comment]
Hi, I have seen the code, and there isn't much to discuss.
But there is one thing, just my personal feeling about it lol. The GUI seems a little disturbing with the account list for regular users. Perhaps you can make it spit to a different window or panel ? And the users can trigger a button or something to open it for the extra features. How do you think about this ? Please let me know, thanks!

**Comment by xnum** [comment]
I've considered the same problem before, we can resize the main form after logon.
the option you mentioned is not bad but the extra window must be hide when logged in,
the final result are same.

**Comment by xnum** [comment]
btw we could discuss it by facebook chat 
https://www.facebook.com/xnumtw

**Comment by kevin940726** [comment]
Not sure if you understand my description. I meant something like [this](https://visualstudiogallery.msdn.microsoft.com/40B89FC7-80FA-4E95-B707-506084F51D6B). there is a button on the login form and when the user click it, the save-account-list you wrote expand to the right side.
Sure, we can chat on facebook, but maybe leave the discussion for this project on github for other potential collaborators to read XD? I mean, this is what the conversation feature is used for, right lol ?

**Comment by xnum** [comment]
got it, I'm not good at UI design, will you do it?

**Comment by kevin940726** [comment]
I'm not good at .NET UI either XDDDD.
That's ok, It will take some time to figure it out. If you have time to do it that will be nice too. Thanks again!

**Comment by kevin940726** [comment]
@xnum : hi, did you make any change?
I've figured out a solution I think is pretty straight forward. Make a button on the login form panel, when the user press it, open another window(or panel) with the multiple-account-list. Double-click on any list-item to load the account to the login form. Only store the account and password to the list when the user checked the "remember password" checkbox after successfully login. There would be little change on the UI, and the flow is more fluent as well as the user experience.
I wonder if you can make this happen? I've just heard that the login flow of Beanfun changed again. After sniffing the package again, I hope that the change won't be big, but I still need some time to implement it. Maybe I can focus on that, and you can take care of the rest?
The next change would be on master branch, and after that, any change made by us can be on development branch first to test the functionality.

**Comment by xnum** [comment]
UI on the commit of my repo shows below
https://youtu.be/zyCWrPLr15k
The different I think is split window and extra button to handle
right side (account list) will be hide after logon
I think it's very similar to your solution.
Due to login flow issue I can't demo it,
whatever, I'm not very interested on modify UI anymore.

I also did repair the keep logged function on my fork,
the key point is to restrart ping worker after login worker or getotp worker were done their tasks.

I noticed that The login flow of Beanfun changed, to fix it, I tried 
1. another user-agent
2. added __VIEWSTATEGENERATOR and it's value
3. assign value to samplerecaptcha
4. assign __EVENTTARGET
but not works perfectly, gl

**Comment by kevin940726** [comment]
I think that is good enough. Thanks, I will pull it down and work on the login flow problem.

**Comment by kevin940726** [comment]
My new version (Node.js) worked lol. There must be some of the redirection bugs in the code.

**Comment by kevin940726** [comment]
Merged into development branch, close.

**Pull request closed without merging**
